### ISSUE TITLE
[Feature] Raspbian Addons

### ISSUE THREAD

**Issue by ryanfortner** [Amog-OS/AmogOS#101]
**Problem:**
The Raspberry Pi Foundation's apt repositories contain limited and outdated software.

**Solution:**
adding the Raspbian Addons apt repository to AmogOS: https://raspbian-addons.org/. It contains updated open-source software not found in the pi foundation's repositories.

**Comment by MarcelskyXD** [comment]
Good idea tbh

**Comment by mobilegmYT** [comment]
I believe the Box86 app from pi-apps installs the repo right? If so, then the repo should already be installed.

**Comment by ryanfortner** [comment]
> I believe the Box86 app from pi-apps installs the repo right? If so, then the repo should already be installed.

The box86 app installs [Itai's repo](https://github.com/Itai-Nelken/weekly-box86-debs). Installation for Raspbian Addons can be found in here: https://docs.raspbian-addons.org/install/

**Comment by mobilegmYT** [comment]
Ah ok. I'll add it to do to the todo list, it'll come out in the holiday release!

**Comment by ryanfortner** [comment]
> Ah ok. I'll add it to do to the todo list, it'll come out in the holiday release!

Great, thanks!
