### ISSUE TITLE
How to install it to Hard Disk

### ISSUE THREAD

**Issue by glowiak** [Amog-OS/AmogOS#102]
As the title says - how I can install AmogOS to my HDD? There's no installer, although 1.4.0 relnotes say that "we added AmogOS installer". I tried to boot from ubunto liveusb and then dd AmogOS iso to /dev/sda from that, but BIOS said "no bootable devices found"

**Comment by mobilegmYT** [comment]
https://github.com/Amog-OS/AmogOS/blob/main/Additional_Notes/AmogOS-x64-installation-README.md#manual-hard-drive-installation

**Comment by glowiak** [comment]
How can I write AmogOS iso to usb on Linux/BSD? I tried dd and unetbootin and it didn't work. What can I do?

**Comment by mobilegmYT** [comment]
> How can I write AmogOS iso to usb on Linux/BSD? I tried dd and unetbootin and it didn't work. What can I do?

Use the manual install method in the readme file i sent
