### ISSUE TITLE
Questions, Answers and Stuff

### ISSUE THREAD

**Issue by Anonymouse2077** [Amog-OS/AmogOS#103]
========= A M O G U S (Questions)

1. How did you add the S U S ascii art when you type neofetch?

2. Where can I get the Theme, Icon, and Wallpaper?

========= S U S (You are being sus at me because im asking these questions)

1. Im asking these questions because I am gonna fork this to Android with Debian 11 Bullseye

2. It looks really cool, so im gonna install this on termux using proot-distro

3. Im gonna use a Minimal Tarball for Debian 11 and copy the AmogOS files to Debian 11 PRoot-Distro.

**Comment by mobilegmYT** [comment]
You make a .txt file, and then edit .config/neofetch/settings.conf and change the distro icon path to the txt.

https://github.com/Amog-OS/AmogOS-Wallpapers
We use papirus icon theme paired with arc-grey-darker I believe
