### ISSUE TITLE
Doesn't follow the SUS standard

### ISSUE THREAD

**Issue by EliasFleckenstein03** [Amog-OS/AmogOS#108]
https://en.wikipedia.org/wiki/Single_UNIX_Specification

**Comment by mobilegmYT** [comment]
~~shhhhh we meet everything except the test suite i just want os to be sus ok~~

**Comment by xcfrg** [comment]
> ~shhhhh we meet everything except the test suite i just want os to be sus ok~

DO IT

**Comment by mobilegmYT** [comment]
> > ~shhhhh we meet everything except the test suite i just want os to be sus ok~
> 
> DO IT

wat

**Comment by lixo-6c69786f** [comment]
YES DO IT

AmogOS will be even more SUS

**Comment by anddddrew** [comment]
amogus sussy baka

**Comment by anddddrew** [comment]
https://amogus.church

**Comment by mobilegmYT** [comment]
Closing since I'll remove sus stuff from readme
