### ISSUE TITLE
[Feature] ATLauncher for X64

### ISSUE THREAD

**Issue by sanswasnthere26** [Amog-OS/AmogOS#109]
I've looked at the source code for ATLauncher and it says it uses GPL3 (http://www.gnu.org/licenses/gpl-3.0.txt) so it would be nice to have on the os as a preinstalled mc launcher?

**Comment by mobilegmYT** [comment]
How thicc is atlauncher

**Comment by sanswasnthere26** [comment]
deb package is 7.28KB and the jar file is 15.76MB

**Comment by mobilegmYT** [comment]
oke, ig it'll go into next release

**Comment by mobilegmYT** [comment]
@sanswasnthere26 
![image](https://user-images.githubusercontent.com/44128563/146707113-5a2b2db7-e3b7-4bb2-99f3-8144f3689bbc.png)

**Comment by mobilegmYT** [comment]
NVM fixed it, preinstall go brrrr
