### ISSUE TITLE
[ANNOUNCEMENT] [ITA/EN] Fake AmogOS websites.

### ISSUE THREAD

**Issue by HelenaMKG** [Amog-OS/AmogOS#115]
_La versione italiana di questo testo è disponibile di seguito, basta scorrere verso il basso._ 

Hello again, everyone. 

We have recently found out about the creation of two fake websites claiming to distribute official versions of AmogOS in Italian. While we will not link to those websites because they contain scams and possibly malware, we will talk about how you should actually redistribute AmogOS and about how you can verify the releases you download. But first off, let's delve into the problem that provoked this discussion.

## The Italian Pretender

On the 4th of January, it came to the attention of the AmogOS team that someone who goes by the name of "Mariow" distributed AmogOS on a fake website while pretending he was the real developer. Mariow is situated in Italy, and he falsely assigned AmogOS copyrights to an unregistered Italian company.

This fake website contained downloads for Mariow's modified versions of AmogOS, including a 32-bit version which was multiarch and (unsurprisingly) did not work. This immediately set off our alarms, and we're currently working on taking down all fake community spaces and websites born from this person (yes, there is more than one!). We have already taken down the main website, and we have contacted YouTube to take down Mariow's videos promoting their fake website and give them a strike.

Mariow also ran a merch store, where they pretended to sell "official" AmogOS merch. This is obviously highly illegal and especially distateful, since as of some weeks ago, we're purely a nonprofit hosted on Open Collective and have completely given up on commercialization.

While we believe in Libre Software and the freedom of redistribution, we simply cannot tolerate our name being used by pretenders and scammers who claim credit for all the work an extremely varied community of creators has built. We are still building a software distribution here; despite AmogOS being a parody system, many people still have interest in it, they download it and use it. Hell, I've even seen someone use it as a rescue CD!

We don't want to discourage people from redistributing, modifying and using AmogOS as their playground, so because of that, we decided to put our basic guidelines into writing in the section below.

## Guidelines for Redistribution

*This section assumes the knowledge of a little terminology.*

If you seek to redistribute a version of AmogOS, you can only call it just "AmogOS" if the checksum of the rootfs bundle (`01-core.sb`) is a match. You can still modify the initramfs and the boot options, add your own customized boot logos and such and still call it just "AmogOS". You cannot, however, claim that you own or that you made AmogOS.

If you want to make your own remix of AmogOS where the checksums do not match, you will need to specify it's a remix. So, for example, "AmogOS Sussy Remix" or something else that disconnects it from the main AmogOS project. For anything else, you can specify it's "like AmogOS" or "AmogOS-based" if you so desire, or not use the name at all. It's libre at the end of the day.

# In italiano

## L'impostore italiano

Il 4 gennaio, è venuto a conoscenza del team di AmogOS che qualcuno che si fa chiamare "Mariow" ha distribuito AmogOS su un sito web falso fingendo di essere il vero sviluppatore. Mariow si trova in Italia e ha falsamente assegnato i diritti d'autore di AmogOS a una società italiana non registrata.

Questo sito fasullo conteneva download per le versioni modificate di AmogOS di Mariow, inclusa una versione a 32 bit che era multiarch e (non sorprendentemente) non funzionava. Questo ha immediatamente fatto scattare i nostri allarmi e attualmente stiamo lavorando per eliminare tutti gli spazi e i siti Web della comunità falsi nati da questa persona (sì, ce n'è più di uno!). Abbiamo già rimosso il sito Web principale e abbiamo contattato YouTube per rimuovere i video di Mariow che promuovono il loro sito Web fasullo e dare loro uno sciopero.

Mariow gestiva anche un negozio di merchandising, dove fingeva di vendere merch "ufficiale" AmogOS. Questo è ovviamente altamente illegale e soprattutto offensivo, dal momento che da alcune settimane fa, siamo puramente un'organizzazione no-profit ospitata su Open Collective e abbiamo completamente rinunciato alla commercializzazione.

Sebbene crediamo nel software Libre e nella libertà di ridistribuzione, semplicemente non possiamo tollerare che il nostro nome venga utilizzato da pretendenti e truffatori che rivendicano il merito per tutto il lavoro che una comunità di creatori estremamente variegata ha costruito. Stiamo ancora costruendo una distribuzione software qui; nonostante AmogOS sia un sistema parodia, molte persone hanno ancora interesse in esso, lo scaricano e lo usano. Diavolo, ho persino visto qualcuno usarlo come CD di ripristino!

Non vogliamo scoraggiare le persone dal ridistribuire, modificare e utilizzare AmogOS come parco giochi, quindi per questo motivo, abbiamo deciso di mettere per iscritto le nostre linee guida di base nella sezione sottostante. 

## Linee guida per la ridistribuzione

*Questa sezione presuppone la conoscenza di un po' di terminologia.*

Se cerchi di ridistribuire una versione di AmogOS, puoi chiamarla solo "AmogOS" se il checksum del bundle rootfs (`01-core.sb`) corrisponde. Puoi ancora modificare le opzioni initramfs e "boot", aggiungere i tuoi loghi di avvio personalizzati e chiamare ancora la tua versione ridistribuita "AmogOS". Non puoi, tuttavia, affermare di possedere o di aver creato AmogOS.

Se vuoi creare il tuo remix di AmogOS in cui i checksum non corrispondono, dovrai specificare che si tratta di un remix. Quindi, ad esempio, "AmogOS Sussy Remix" o qualcos'altro che lo disconnette dal progetto AmogOS principale. Per qualsiasi altra cosa, puoi specificare che è "come AmogOS" o "basato su AmogOS" se lo desideri, o non usare affatto il nome. È libre alla fine della giornata.

**Comment by mobilegmYT** [comment]
> We are still building a software distribution here; despite AmogOS being a parody system, many people still have interest in it, they download it and use it. Hell, I've even seen someone use it as a rescue CD!

Can confirm also, I once used AmogOS to repair my hard drive and reset the admin account password because all the other live images I had on hand didn't work 😆.

**Comment by AleTv73** [comment]
**Hello! I'm AleTv73 from the Fake AmogOS staff, We of the staff did not know that Mariow He had copied the os to you, we the staff We are very sorry, but we have been deceived.

Sorry For my English.

-AleTv+73**

**Comment by Sniper10754** [comment]
I am the one who discovered Mariow and reported that to the staff 👍🏻

**Comment by SoulRepo** [comment]
i guess you can say... it was an imposter

**Comment by mobilegmYT** [comment]
> i guess you can say... it was an imposter

Their italian... so it was an impasta

**Comment by Sniper10754** [comment]
> > i guess you can say... it was an imposter
> 
> 
> 
> Their italian... so it was an impasta

![image](https://user-images.githubusercontent.com/74132494/148935625-0880cb89-df9c-4230-9aad-d1670609ddd0.jpeg)
