### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Fogapod** [Amog-OS/AmogOS#116]
Hello, there are download links, but I can't find source code anywhere. Is it publically available?

**Comment by mobilegmYT** [comment]
There is no "source code". The apps are all open source and you can get the themes by extracting rootfs

**Comment by Fogapod** [comment]
It would be nice to have configuration hosted somewhere in accessible form to avoid downloading entire iso if you're only interested in one config

**Comment by mobilegmYT** [comment]
> It would be nice to have configuration hosted somewhere in accessible form to avoid downloading entire iso if you're only interested in one config

There's quite alot of custom congiuration files and also lots of other files linked to them, would be a nightmare to upload all of it.
