### ISSUE TITLE
[Feature] Windows destroyer

### ISSUE THREAD

**Issue by paledega** [Amog-OS/AmogOS#121]
https://gitlab.com/sulinos/devel/sulin-sources/-/blob/master/destroy-winzort.sh

This script automatically search and destroy winzort. Please add and autorun with live boot.

**Comment by Caticer** [comment]
Nani tf

**Comment by sanswasnthere26** [comment]
what the fuck, how is this a enhancement at all, prob kids are trying to load this os and you want them to nuke their only windows install? that's kind of scummy bro

**Comment by mobilegmYT** [comment]
> what the fuck, how is this a enhancement at all, prob kids are trying to load this os and you want them to nuke their only windows install? that's kind of scummy bro

Good, that's what the puny dumb kids get for using windows instead of Linux, who cares if they have important school files? Everyone must bow down the daddy Linus Borvalds and Richard Stallwoman.

**Comment by paledega** [comment]
We can changi distroy method. We can remove /Windows and /Program\ Files directories inside of formating disk.

May we create counter and system well destroyed if counter reach a number :) Users dont know why onw sysüem removed.

**Comment by paledega** [comment]
And it should be hidden feature I think.

**Comment by Jamchuck09** [comment]
> > what the fuck, how is this a enhancement at all, prob kids are trying to load this os and you want them to nuke their only windows install? that's kind of scummy bro
> 
> Good, that's what the puny dumb kids get for using windows instead of Linux, who cares if they have important school files? Everyone must bow down the daddy Linus Borvalds and Richard Stallwoman.

That is scummy I run windows because software I need for work is on windows, but I dual boot lubuntu and windows so I can run Linux software as well

**Comment by Jamchuck09** [comment]
> https://gitlab.com/sulinos/devel/sulin-sources/-/blob/master/destroy-winzort.sh
> 
> This script automatically search and destroy winzort. Please add and autorun with live boot. 
> 
> 

I reported you for putting malware in amog os
