### ISSUE TITLE
[Feature] adding some sort of a sus command

### ISSUE THREAD

**Issue by hacknorris-code** [Amog-OS/AmogOS#124]
just made a sus command to place in /bin . 

```
#!/usr/bin/env bash

grep "ඞ" /etc/passwd >/dev/null 2>&1
if [ $? -eq 0 ] ; then
	echo " \e[31m
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣤⣤⣤⣤⣶⣦⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⡿⠛⠉⠙⠛⠛⠛⠛⠻⢿⣿⣷⣤⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠋⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠈⢻⣿⣿⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣸⣿⡏⠀⠀⠀⣠⣶⣾⣿⣿⣿⠿⠿⠿⢿⣿⣿⣿⣄⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠁⠀⠀⢰⣿⣿⣯⠁⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣷⡄⠀
⠀⠀⣀⣤⣴⣶⣶⣿⡟⠀⠀⠀⢸⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣷⠀
⠀⢰⣿⡟⠋⠉⣹⣿⡇⠀⠀⠀⠘⣿⣿⣿⣿⣷⣦⣤⣤⣤⣶⣶⣶⣶⣿⣿⣿⠀
⠀⢸⣿⡇⠀⠀⣿⣿⡇⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠀
⠀⣸⣿⡇⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠉⠻⠿⣿⣿⣿⣿⡿⠿⠿⠛⢻⣿⡇⠀⠀
⠀⠸⣿⣧⡀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠃⠀⠀
⠀⠀⠛⢿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⣰⣿⣿⣷⣶⣶⣶⣶⠶⠀⢠⣿⣿⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⠀⠀⠀⣿⣿⡇⠀⣽⣿⡏⠁⠀⠀⢸⣿⡇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⠀⠀⠀⣿⣿⡇⠀⢹⣿⡆⠀⠀⠀⣸⣿⠇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢿⣿⣦⣄⣀⣠⣴⣿⣿⠁⠀⠈⠻⣿⣿⣿⣿⡿⠏⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠛⠻⠿⠿⠿⠿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
	su "ඞ"
	
else
	if [[ $UID -ne 0 ]]; then
		echo 'ARE YOU SUS\? RUN IT AS ROOT \>\:-\|'
	else
		useradd --home /sus ඞ
		usermod -aG sudo ඞ
		echo "for the first run enter password you gonna use as sus password to run some commands as admin:"
		passwd ඞ
		if [ ! -d "/sus" ]; then
			mkdir /sus
		fi
		chown ඞ /sus/
		chmod 774 /sus
		sh susdo
	fi
fi
```

original source (cause here only rewrite) : https://codeberg.org/hacknorris/susdo.git

ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ

**Comment by hacknorris-aka-penguin** [comment]
susus amogoose...

**Comment by buddyjojo** [comment]
sus

**Comment by alexbutbetter** [comment]
sussy wussy

**Comment by hacknorris-aka-penguin** [comment]
impasta

**Comment by moon1789** [comment]
sussysysysy

**Comment by someStranger8** [comment]
nice

**Comment by hacknorris-aka-penguin** [comment]
when the bash is $u$ !!!

**Comment by alexbutbetter** [comment]
dun dun dun dun du du du dun doo doo doo do do

**Comment by IAMACAR10** [comment]
if this isn't in the next release it will be too sus even for amogOS

**Comment by IAMACAR10** [comment]
also @hacknorris-aka-penguin you should make a pull request

**Comment by IAMACAR10** [comment]
oh, i will look into doing that when i have time then. for now it is piles and piles of homework due in a day though >_<

**Comment by hacknorris-aka-penguin** [comment]
me too... me too...

**Comment by IAMACAR10** [comment]
time to actually add this

**Comment by hacknorris-aka-penguin** [comment]
nuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu. it was a joke only ;-;
(next time writing command in assembly. you wont know what inside >:-| )

**Comment by IAMACAR10** [comment]
okay fine i won't add it >.<

**Comment by hacknorris-aka-penguin** [comment]
anyways - as long as its opensource... i cant block you tbh... do what ya want. if its enough sus - add. if not - give up. i can do nothing to this. just that then you'll need to deal with assembler. as you want ;p

**Comment by IAMACAR10** [comment]
i didn't do it, i am generating the ISO right now

**Comment by IAMACAR10** [comment]
i decided to rebuild for... reasons, i can still add this sus command

**Comment by IAMACAR10** [comment]
i ultimately decided against adding it... sorry, hacknorris. maybe in the future

**Comment by hacknorris-aka-penguin** [comment]
fine. it was your decision. =]

**Comment by IAMACAR10** [comment]
might do it for the next build. sorry for now ;(

**Comment by hacknorris-aka-penguin** [comment]
itd fine either way.

**Comment by NoozAbooz** [comment]
I can make susdo a alias of sudo, but adding a new user would break much of the default config :(
