### ISSUE TITLE
dead os

### ISSUE THREAD

**Issue by moon1789** [Amog-OS/AmogOS#129]
bring back amogos from dead

**Comment by sanswasnthere26** [comment]
i say we kick nooz out

**Comment by F-fengzi** [comment]
when nodead

**Comment by buddyjojo** [comment]
> i say we kick nooz out

agreed

**Comment by buddyjojo** [comment]
eh not existing is better then it sucking

**Comment by buddyjojo** [comment]
bruh

**Comment by moon1789** [comment]
I can kick everyone out

**Comment by moon1789** [comment]
![image](https://user-images.githubusercontent.com/72432771/156300718-60c77d00-1b25-4ea2-a37f-24d29d9660fb.png)

**Comment by sulincix** [comment]
We can create iso with github actions. 
For example: puffos iso created every day with github actions.
https://github.com/PuffOS/teaiso-profile/blob/master/.github/workflows/blank.yml

**Comment by moon1789** [comment]
Mhmh

**Comment by moon1789** [comment]
undead when

**Comment by F-fengzi** [comment]
nvr

**Comment by buddyjojo** [comment]
amogos: become jostro

**Comment by F-fengzi** [comment]
jostro [əˈməNG əs]
adj. The state of an object that is dead.
n. Death.

**Comment by moon1789** [comment]
bt dd

**Comment by moon1789** [comment]
engsh

**Comment by abs007** [comment]
sus

**Comment by buddyjojo** [comment]
sussy

**Comment by F-fengzi** [comment]
sussy wussy

**Comment by nikatark** [comment]
still no way to run AmogOS on ventoy?
