### ISSUE TITLE
Taking a break.

### ISSUE THREAD

**Issue by moon1789** [Amog-OS/AmogOS#130]
I've decided that I won't work on Amogos until 2025 since the "education pressure" is very intense here . I find no time to work on the OS, therefore I have ask nooz, Fengzi, and Jojo Autoboy to take over the project while I am away.

Thank you very much for the support,
Moon1789.

**Comment by IAMACAR10** [comment]
I hope all goes well for you, moon
i trust nooz and jojo autoboy to make OS great again
lol (lots of love), -tax fraud
