### ISSUE TITLE
[Feature] Change Firefox Icon

### ISSUE THREAD

**Issue by Robby9705** [Amog-OS/AmogOS#132]
https://hacks.mozilla.org/2021/02/heres-whats-happening-with-the-firefox-nightly-logo/

Ok So I've Made One In Inkscape, I Would Have Made A Pull Request But I Don't Know How To Code T-T
[Amogus-Browser-Logo-Assets.zip](https://github.com/Amog-OS/AmogOS/files/8534255/Amogus-Browser-Logo-Assets.zip)

**Comment by IAMACAR10** [comment]
we should fork firefox and make a sussy browser. i don't have much experience with that, but I do have the firefox source code (from ~1 month ago) on my computer because I was interested in forking firefox. Maybe now i could finally make a sussy wussy browser

**Comment by IAMACAR10** [comment]
https://github.com/IAMACAR10/papisus

papirus icon themes with the firefox icon susified. i haven't tested if the theme works yet, but it should

**Comment by NoozAbooz** [comment]
coming in new build :)
