### ISSUE TITLE
Code Uploading

### ISSUE THREAD

**Issue by Colack** [Amog-OS/AmogOS#142]
You should upload the source code to this repository, so that people could actually help with the source code.

Thanks,
- Colack

**Comment by mobilegmYT** [comment]
> You should upload the source code to this repository, so that people could actually help with the source code.
> 
> Thanks,
> 
> * Colack

The OS is a UI mod strictly, so there is no actual source code. The icon themes and other ui elements we use are listed in readme

**Comment by Colack** [comment]
hmm... Ok

**Comment by mobilegmYT** [comment]
The main thing is that I physically don’t have access to the code. AmogOS
is based on Debian though, so feel free to download AmogOS and modify the
rootfs or modify Debian source code.
