### ISSUE TITLE
Not compatible with Raspberry Pi 5

### ISSUE THREAD

**Issue by Project516** [Amog-OS/AmogOS#173]
Booting gives an error that reads its not compatible with raspberry pi 5

**Comment by Everytab** [comment]
This is because the latest version of AmogOS was released before the Raspberry Pi 5 was even announced. There is a small chance that a future 1.x release might be made just for a Raspberry Pi 5, but complications exist.

TLDR - no pi 5 support (for now, unconfirmed if it will ever be added)
