### ISSUE TITLE
Bro that rick roll gave me jumpscare

### ISSUE THREAD

**Issue by AzikDeveloper** [Amog-OS/AmogOS#83]
lower the music

**Comment by buddyjojo** [comment]
no :)

**Comment by Crewmategamingcoding** [comment]
make it play all i want for Christmas is you in December :trollface:

**Comment by mobilegmYT** [comment]
Sure :)

**Comment by buddyjojo** [comment]
> Sure :)

now thats evil

**Comment by mobilegmYT** [comment]
> > Sure :)
> 
> now thats evil

https://www.youtube.com/watch?v=lQHFuqDRdLE
