### ISSUE TITLE
[x64 bug] VBox machine not saving downloads after shutoff

### ISSUE THREAD

**Issue by greped** [Amog-OS/AmogOS#84]
Used the iso image in VBox, runs just fine. The problem is that my machine resets itself (i.e. loses all caches, downloads, etc) after powering off. Below is a picture of the info panel on VBox. What can I change so that I'm able to save files even after shutting down my machine?

https://imgur.com/a/92hMFPD

**Comment by mobilegmYT** [comment]
Use the VM files we provide in the release

**Comment by mobilegmYT** [comment]
https://drive.google.com/file/d/195dFrFehCxefzy1JbYFO6MzIC90QegFT/view?usp=sharing
