### ISSUE TITLE
[x64 bug]

### ISSUE THREAD

**Issue by GYKgamer** [Amog-OS/AmogOS#86]
My error is that when I try to boot off of the usb it boots but when I try to install it's stuck on "looking for linux data /linux" and then says a fatal error occurred could not locate linux data  
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 -  1.4.0
 - the laptop i'm testing with is a HP Pavilion dv6-6c50us

**Additional context**
I'm using a free tool called ventoy to boot into the usb as flashing the usb gave me another error

**Comment by mobilegmYT** [comment]
How did you install it?

**Comment by GYKgamer** [comment]
I haven't yet

**Comment by GYKgamer** [comment]
"My error is that when I try to boot off of the usb it boots but when I try to install it's stuck on "looking for linux data /linux" and then says a fatal error occurred could not locate linux data"

**Comment by mobilegmYT** [comment]
I mean how did you flash it

**Comment by GYKgamer** [comment]
I used a tool called ventoy

**Comment by GYKgamer** [comment]
Since when I tried using rufus it failed

**Comment by mobilegmYT** [comment]
Use universal USB imager

**Comment by GYKgamer** [comment]
ok I'll update you later

**Comment by GYKgamer** [comment]
thanks this fixed the problem for now
