### ISSUE TITLE
readme.txt not there

### ISSUE THREAD

**Issue by thunderpants** [Amog-OS/AmogOS#88]
https://github.com/Amog-OS/AmogOS/blob/main/Additional_Notes/AmogOS-x64-installation-README.txt
Also, what is this UNIVERSAL USB IMAGER ?
Unless you mean Universal USB Installer ?

**Comment by mobilegmYT** [comment]
Whoops, brain fart. Sorry bout that

**Comment by mobilegmYT** [comment]
> https://github.com/Amog-OS/AmogOS/blob/main/Additional_Notes/AmogOS-x64-installation-README.txt
> Also, what is this UNIVERSAL USB IMAGER ?
> Unless you mean Universal USB Installer ?
> 
> 

Where do you see universal USB imager? Can't find it in the file

**Comment by mobilegmYT** [comment]
Also readme.txt might be under a different name in the zip

**Comment by thunderpants** [comment]
It says on the main github page ."don't use Rufus ,use universal USB imager"
