### ISSUE TITLE
Sus issue

### ISSUE THREAD

**Issue by Milk-Cool** [Amog-OS/AmogOS#89]
http://totally-not-a-rickroll.gq

**Comment by Nostorian** [comment]
smh

**Comment by Nostorian** [comment]
atleast check the links before you post them so they aren't obvious lmfao

**Comment by Nostorian** [comment]
smthing like this: [https://github.com/Amog-OS/AmogOS/issues/89](https://www.youtube.com/watch?v=ub82Xb1C8os)

**Comment by buddyjojo** [comment]
bruh
