### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by sarnthilIsHorny** [Amog-OS/AmogOS#90]
Debloat Windows 10 and we can than have AmogOS Win 10(You can just take inspiration from some of custom OSes.The best ones are atlas and ggOS).Would be gr8 for amog us enjoyers who don't wanna use a linux distro.TY ;D

**Comment by mobilegmYT** [comment]
Windows sucks

Linux pog 😎 
(also bro how the heck would you theme windows like I'm fairly sure that's not possible without dark magic)

**Comment by sarnthilIsHorny** [comment]
> Windows sucks
> 
> Linux pog 😎 (also bro how the heck would you theme windows like I'm fairly sure that's not possible without dark magic)

![unknown](https://user-images.githubusercontent.com/94053086/142336360-48195931-437f-4066-9708-ca2b96eba653.png)‌‌
https://atlasos.net/​​‌​​‌‌‌​‌‌‌​‌‌​​​​‌​‌‌​‌​​​​‌‌​‌‌​‌​‌​‌‌​​​​‌​‌‌​​​​​‌‌​​​​

**Comment by mobilegmYT** [comment]
Well I would like the ability to change more than just the wallpaper. There's also no way for me to package the OS.

**Comment by sarnthilIsHorny** [comment]
> Well I would like the ability to change more than just the wallpaper. There's also no way for me to package the OS.

i meant the os it debloated not just wallpapers but ok. :/
