### ISSUE TITLE
no issues so i created one

### ISSUE THREAD

**Issue by moon1789** [Amog-OS/AmogOS#92]

**Comment by buddyjojo** [comment]
moon your exactly 57 days late for that suse build i requested
you know what that means :)

**Comment by Samisafool** [comment]
SUSe

**Comment by Zekiah-A** [comment]
sussy wussy

**Comment by andy840119** [comment]
sus

**Comment by PF94** [comment]
when my old computer is sus

**Comment by buddyjojo** [comment]
i should sus my 2005 pc one day

**Comment by RioRocker97** [comment]
i SUSgest to close this iSUSues
