### ISSUE TITLE
When the license is sus

### ISSUE THREAD

**Issue by gkgoat1** [Amog-OS/AmogOS#96]
License conflict: https://git.sr.ht/~martijnbraam/among-sus/tree/master/item/LICENSE

plz fix

**Comment by gkgoat1** [comment]
@moon1789 plz fix before i call GitHub and tell them u are pirating

**Comment by mobilegmYT** [comment]
> License conflict: https://git.sr.ht/~martijnbraam/among-sus/tree/master/item/LICENSE
> 
> plz fix

Hi, I couldn't find much on the affero license, so could you specify which part we are violating?

**Comment by gkgoat1** [comment]
In the binaries you release (I presume so), `among-sus` is packaged as a binary only. If you have a link to the source *in the iso*, I will close this issue.

**Comment by mobilegmYT** [comment]
> In the binaries you release (I presume so), `among-sus` is packaged as a binary only. If you have a link to the source _in the iso_, I will close this issue.

What do you think would be the best way to unintrusively add in source link? I'd be happy to modify it to print out the link to the source code when run.

**Comment by gkgoat1** [comment]
I think you could create a `CREDITS` file and include that notice.

**Comment by mobilegmYT** [comment]
Where? I think printing it out to shell would be quicker and more accessible for users.

**Comment by gkgoat1** [comment]
Maybe in a folder for source files, like `/usr/include`. I'm not sure what would happen if you cloned `among-sus` there.

**Comment by mobilegmYT** [comment]
I think i'll just print it out to shell or something to make it less of a hassle

**Comment by gkgoat1** [comment]
Remember to distribute the forked code :)

**Comment by mobilegmYT** [comment]
> Remember to distribute the forked code :)

~~nah ill just make it so the binary will be a bash script that'll print it out and run the real binary hehe~~
