### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by JyanJohn** [Amog-OS/AmogOS#98]
Hello, can you upload a aarch64 or ARM64 Tarball for this, because I want to install it on Android, if not can you please send the settings, and theme;)

**Comment by mobilegmYT** [comment]
This is a armhf os designed for raspberry pi systems so definitely will not work, you could try a termux proot. If you wanna get the wallpaper and icon, use https://github.com/jostroOS/AmogOS-Wallpapers.

**Comment by 53jk1** [comment]
ඞ
